### PR TITLE
Fix depth registeration 

### LINKED ISSUE #2234: cv2.rgbd.registerDepth wraps pixels beyond boundary
##### System information (version)
- opencv-contrib-python-4.1.0.25
- Operating System / Platform => Ubuntu 14.04

##### Detailed description

When using cv2.rgbd.registerDepth() to register a depth map into a color image with larger field of view, the depth map periodically repeats beyond its field of view.

registerDepthBug

##### Steps to reproduce
```
import numpy as np
import cv2
import matplotlib.pyplot as plt


# my implementaion that produces the expected output
def registerDepth(intrinsics_depth, intrinsics_color, dist_coef_color, extrinsics, depth, shape, depthDilation):
    assert dist_coef_color is None
    assert depthDilation==False

    width, height = shape
    out = np.zeros((height,width))/0
    y,x = np.meshgrid(np.arange(depth.shape[0]), np.arange(depth.shape[1]), indexing='ij')
    x=x.reshape(1,-1)
    y=y.reshape(1,-1)
    z=depth.reshape(1,-1)
    x=(x-intrinsics_depth[0,2])/intrinsics_depth[0,0]
    y=(y-intrinsics_depth[1,2])/intrinsics_depth[1,1]
    pts = np.vstack((x*z,y*z,z))
    pts = extrinsics[:3,:3]@pts+extrinsics[:3,3:]
    pts = intrinsics_color@pts
    px = np.round(pts[0,:]/pts[2,:])
    py = np.round(pts[1,:]/pts[2,:])
    mask = (px>=0) * (py>=0) * (px<width) * (py<height)
    out[py[mask].astype(int),px[mask].astype(int)] = pts[2,mask]
    return out



def main():
    # start with an image with resolution 100x100
    # register it to an image of resolution 100x400

    intrinsics_depth = np.array([[100, 0, 50],
                                 [0, 100, 50],
                                 [0, 0, 1]], dtype=float)
    intrinsics_color = np.array([[100, 0, 200],
                                 [0, 100, 50],
                                 [0, 0, 1]], dtype=float)
    dist_coef_color = None
    extrinsics = np.eye(4)
    depth = np.repeat(np.arange(100)[None,:],100,0).astype(float)
    height, width = 100, 400

    depth1 = cv2.rgbd.registerDepth(intrinsics_depth, intrinsics_color, dist_coef_color, extrinsics, depth, (width, height), depthDilation=False)
    depth2 = registerDepth(intrinsics_depth, intrinsics_color, dist_coef_color, extrinsics, depth, (width, height), depthDilation=False)

    plt.subplot(1,3,1)
    plt.imshow(depth)
    plt.title('input')
    plt.subplot(1,3,2)
    plt.imshow(depth1)
    plt.title('cv2 output')
    plt.subplot(1,3,3)
    plt.imshow(depth2)
    plt.title('expected output')
    plt.show()

main()
```

### PR DESCRIPTION
**Pull request by ayushgargdroid**
Fixes #2234
relates #132

The for loop was iterating redundantly which caused it to wrap pixels around boundaries when the color image has a larger field of view than the depth image. 

Also added a test case for the same.

**Before**
63403041-6d6cd000-c392-11e9-8a2f-36956075d5ac

**After**
Figure_1

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] The feature is well documented and sample code can be built with the project CMake
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.

### CODE REVIEW

File: modules/rgbd/test/test_registration.cpp [hunk 1]
```diff
@@ -113,5 +113,26 @@ TEST(Rgbd_DepthRegistration, compute)
...
+            depthMat(i-1,j-1) = (float)j;
+    }
+
+    Mat registeredDepth;
+    registerDepth(intrinsicsDepth, intrinsicsColor, Mat(), Matx44f::eye(), depthMat, Size(400, 100), registeredDepth);
+    
+    Rect roi( 150, 0, 100, 100 );  
+    Mat subM(registeredDepth,roi);
+    
+    ASSERT_TRUE(cv::countNonZero(subM==depthMat)==100*100);
```
Comment (alalek) [inline modules/rgbd/test/test_registration.cpp]: Please use this check for bitexact:
```
EXPECT_EQ(0, cvtest::norm(subM, depthMat, NORM_INF));
```

File: modules/rgbd/test/test_registration.cpp [hunk 2]
```diff
@@ -113,5 +113,26 @@ TEST(Rgbd_DepthRegistration, compute)
   test.safe_run();
 }
 
+TEST(Rgbd_DepthRegistration, issue_2234)
+{
+    Mat intrinsicsDepth = (Mat_<float>(3, 3) << 100., 0., 50., 0., 100., 50., 0., 0., 1.);
+    Mat intrinsicsColor = (Mat_<float>(3, 3) << 100., 0., 200., 0., 100., 50., 0., 0., 1.);
```
Comment (alalek) [inline modules/rgbd/test/test_registration.cpp]: Consider using `Matx33f` instead.

**Comment by alalek** [comment]
As a "bugfix" this patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".
