### PR TITLE
optflow: add a check for 3 channel images for sparse RLOF

### LINKED ISSUE #2087: A bug of opencv4.1?
##### Detailed description

I think this is a bug about the new function `calcOpticalFlowSparseRLOF` introduced in opencv4.1, so I submit an issue here(and it is a cross post [here](http://answers.opencv.org/question/211429/a-bug-of-opencv410/)):

##### Steps to reproduce

	Mat pre = imread("C:/Users/Lenovo/Desktop/33.png", 0);
	Mat next = imread("C:/Users/Lenovo/Desktop/44.png", 0);
	resize(next, next, pre.size());
	vector<Point2f> points[2];

	goodFeaturesToTrack(pre, points[0], 20, 0.01, 5);

	vector<uchar> status;
	Mat err;
	calcOpticalFlowSparseRLOF(pre, next, points[0], points[1], status, err);
This is my two images:

pre:
image description

next:
image description

But whatever I run the code how much time, I cannot get nothing. Is it a bug or I missed something?
@tsenst

### PR DESCRIPTION
**Pull request by berak**
(hopefully) resolves #2087

3 channel images are required for the (default) SR_CROSS RLOF optflow implementation, add a check for the sparse version similar [to the dense one here](https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/src/rlofflow.cpp#L117)

### CODE REVIEW

File: modules/optflow/src/rlofflow.cpp [hunk 1]
```diff
@@ -281,6 +281,8 @@ class SparseRLOFOpticalFlowImpl : public SparseRLOFOpticalFlow
         CV_Assert(!prevImg.empty() && prevImg.depth() == CV_8U && (prevImg.channels() == 3 || prevImg.channels() == 1));
         CV_Assert(!nextImg.empty() && nextImg.depth() == CV_8U && (nextImg.channels() == 3 || nextImg.channels() == 1));
         CV_Assert(prevImg.sameSize(nextImg));
+        if ((param->supportRegionType == SR_CROSS) && (prevImg.channels() != 3 || nextImg.channels() != 3))
```
Comment (alalek) [inline modules/optflow/src/rlofflow.cpp]: Need to check for empty `param` here to avoid crash.
Will add PR soon.

/cc @tsenst
