### PR TITLE
fix(wechat_code): Modify `isnan` for compatibility with -ffast_math.

### LINKED ISSUE #3150: We chat QR Scan crashes with certain images.
##### System information (version)

- OpenCV => 4.5.4
- Operating System / Platform => Ubuntu 20.04
- Compiler => Visual Studio Code 1.63.2

##### Detailed description

I've implemented the WeChat QR Code Scanner in a similar fashion to the one included in guides such as [this one](https://learnopencv.com/wechat-qr-code-scanner-in-opencv/) and [this one](http://www.wechatcv.com/) (C++ implementations). The QR scanner seems to work in general, but we have noticed occasions where  the process just crashes silently. After launching the script in debugging mod we have cached the following errors:

`Object "/usr/local/lib/libopencv_wechat_qrcode.so.4.5", at 0x7fae230675ca, in cv::wechat_qrcode::WeChatQRCode::detectAndDecode[abi:cxx11](cv::_InputArray const&, cv::_OutputArray const&)`

`   Object "/usr/local/lib/libopencv_wechat_qrcode.so.4.5", at 0x7fae23066fdb, in cv::wechat_qrcode::WeChatQRCode::Impl::decode[abi:cxx11](cv::Mat const&, std::vector<cv::Mat, std::allocator<cv::Mat> >&, std::vector<cv::Mat, std::allocator<cv::Mat> >&)`

`Thread 1 "qr_scan" received signal SIGSEGV, Segmentation fault.
0x00007ffff7cc1097 in zxing::qrcode::Detector::sizeOfBlackWhiteBlackRun(int, int, int, int) () from target:/usr/local/lib/libopencv_wechat_qrcode.so.4.5
`

##### Steps to reproduce

For reproducing, you can use the scanner method `detectAndDecode` with the following image. We have found that this image manages to crash the scanner:
aiuda

### PR DESCRIPTION
**Pull request by Konano**
fix #3150
Merge with https://github.com/opencv/opencv/pull/23881

Reference: https://stackoverflow.com/questions/7263404/mingw32-stdisnan-with-ffast-math

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/wechat_qrcode/src/zxing/zxing.hpp [hunk 1]
```diff
@@ -54,8 +54,14 @@ typedef unsigned char boolean;
 #include <cmath>
 
 namespace zxing {
-inline bool isnan(float v) { return std::isnan(v); }
-inline bool isnan(double v) { return std::isnan(v); }
+inline bool isnan(float v) { 
+    union { float v; uint32_t x; } u = { v };
+    return (u.x & 0x7fffffffu) > 0x7f800000u;
+}
+inline bool isnan(double v) {
```
Comment (opencv-alalek) [inline modules/wechat_qrcode/src/zxing/zxing.hpp:61]: Lets reuse OpenCV implementation: https://github.com/opencv/opencv/blob/4.7.0/modules/core/include/opencv2/core/fast_math.hpp#L284

**Comment by asmorkalov** [comment]
@Konano Friendly reminder.

File: modules/wechat_qrcode/src/zxing/zxing.hpp [hunk 2]
```diff
@@ -54,8 +54,14 @@ typedef unsigned char boolean;
...
-inline bool isnan(float v) { return std::isnan(v); }
-inline bool isnan(double v) { return std::isnan(v); }
+inline bool isnan(float v) { 
+    union { float v; uint32_t x; } u = { v };
+    return (u.x & 0x7fffffffu) > 0x7f800000u;
+}
+inline bool isnan(double v) { 
+    union { double v; uint64_t x; } u = { v };
+    return (u.x & ~0x8000000000000000uLL) > 0x7ff0000000000000uLL;
+}
```
Comment (Konano) [inline modules/wechat_qrcode/src/zxing/zxing.hpp:64]:
```suggestion
inline bool isnan(float v) { return cvIsNaN(v); }
inline bool isnan(double v) { return cvIsNaN(v); }
```

I called `cvIsNaN()` directly but it doesn't seem to work, it still crashed in the local test.

Comment (Konano) [reply modules/wechat_qrcode/src/zxing/zxing.hpp:64]: @asmorkalov @opencv-alalek Need help.

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by Konano** [comment]
@asmorkalov @opencv-alalek Any new progress?
