### PR TITLE
Fix rounding in StructuredEdgeDetection

### LINKED ISSUE #881: Memory leak and bug in Structured Edge Detector
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

We found a bug in Structured Edge Detector which also creates a memory leak.
in structured_edge_detection.cpp line 246 the code is:
      `pHist[cvRound((j/pSize + pPhase[j])*nBins)] += pMagn[j] / CV_SQR(pSize);`

this creates an unintentional writing to memory outside the histogram Mat as well as introducing an error in the histogram itself.
when pPhase[j] > 0.875 the cvRound causes the pointer to point to the adjacent pixel.

our solution was to change the code:
      `pHist[cvRound((j / pSize + pPhase[j] * 0.9999 - 0.124999)*nBins)] += pMagn[j] / CV_SQR(pSize);`

##### Steps to reproduce

reproducing the bug is straight forward. 
to reproduce the memory leak, one must use an image where the value of one of the four lower right pixels of the phase Mat has a value > 0.875.

### PR DESCRIPTION
**Pull request by sovrasov**
Resolves #881

### CODE REVIEW

File: modules/ximgproc/src/structured_edge_detection.cpp [hunk 1]
```diff
@@ -243,7 +245,7 @@ static void gradientHist(const cv::Mat &src, cv::Mat &magnitude, cv::Mat &histog
         float *pHist = histogram.ptr<float>(i/pSize);
 
         for (int j = 0; j < phase.cols; ++j)
-            pHist[cvRound((j/pSize + pPhase[j])*nBins)] += pMagn[j] / CV_SQR(pSize);
+            pHist[cvRound((j/pSize + pPhase[j]*phaseRoundingCoeff - phaseRoundingShift)*nBins)] += pMagn[j] / CV_SQR(pSize);
```
Comment (alalek) [inline modules/ximgproc/src/structured_edge_detection.cpp]: We can use something like this in case of occasional out of range results in floating point calculations:
```
size_t index  = cvRound(... accurate formula without magic coefficients ...)
index = max(0, min(index, <sizeof pHist> - 1));
pHist[index] = ...
```

**Comment by alalek** [comment]
:+1:
