### PR TITLE
KinFu fix (iss2925)

### LINKED ISSUE #2925: KinFu render() error (python3.8)
##### System information (version)

- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019 (for building python library)
- PyCharm 2020.3
- Python 3.8

##### Detailed description

Python version of kinfu.render works only with 2 args, while it should work with 1 and with 2

##### Steps to reproduce

    ```
    params = cv2.kinfu_Params.defaultParams()
    kf = cv2.kinfu_KinFu.create(params)
    flag = kf.update(depth)
    size = height, width, 4
    cvt8 = np.zeros(size, dtype=np.uint8)
    kf.render(cvt8)
    ```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by DumDereDum**
### Pull Request Readiness Checklist

resolves #2925

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/rgbd/include/opencv2/rgbd/kinfu.hpp [hunk 1]
```diff
@@ -208,8 +218,8 @@ class CV_EXPORTS_W KinFu
         which is a last frame camera pose.
     */
 
-    CV_WRAP virtual void render(OutputArray image, const Matx44f& cameraPose = Matx44f::eye()) const = 0;
-
+    CV_WRAP virtual void render(OutputArray image, const Matx44f& cameraPose) const = 0;
+	//TODO: rewrite render() for 1 and 2 args, like update()/updateT()
```
Comment (savuor) [inline modules/rgbd/include/opencv2/rgbd/kinfu.hpp:222]: please remove this TODO

**Comment by savuor** [comment]
👍
