### PR TITLE
Bug fixes: using mask with BinaryDescriptor 

### LINKED ISSUE #1437: Code crashes while computing line descriptors for tracked lines
##### System information (version)

- OpenCV => 3.2.0 (installed as ros-kinetic-opencv3)
- Operating System / Platform => Ubuntu 64 Bit
- Compiler => g++/gcc version 5.4.0 20160609

##### Detailed description

I'm trying to compute LBD descriptor for detected line segments in an image. My code crashes on calling the compute function of the BinaryDescriptor class. It works for the first one or two iterations after which it crashes. I have ensured that the arguments are not empty or NULL. On running it with valgrind I found that it crashes in the computeLBD function.
##### Steps to reproduce
This is the code block that's causing the program to crash

```.cpp
Mat prevDescriptors;
if(!mPrevFrame.empty() and !prevTrackedPoints.empty())
{
        Ptr<BinaryDescriptor> lbd = BinaryDescriptor::createBinaryDescriptor();
        lbd->compute(mPrevFrame, prevTrackedLines, prevDescriptors);
}
```
where mPrevFrame and prevTrackedLines are calculated elsewhere. On running with valgrind, this is the output that I get.
```
==24290== Invalid read of size 4
==24290==    at 0x7E76238: cv::line_descriptor::BinaryDescriptor::computeLBD(std::vector<std::vector<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine, std::allocator<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine> >, std::allocator<std::vector<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine, std::allocator<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine> > > >&, bool) (in /opt/ros/kinetic/lib/libopencv_line_descriptor3.so.3.2.0)
==24290==    by 0x7E7ABC5: cv::line_descriptor::BinaryDescriptor::computeImpl(cv::Mat const&, std::vector<cv::line_descriptor::KeyLine, std::allocator<cv::line_descriptor::KeyLine> >&, cv::Mat&, bool, bool) const (in /opt/ros/kinetic/lib/libopencv_line_descriptor3.so.3.2.0)
```

I downloaded the required source files from the opencv_contrib repository for Line Descriptors and this is the output after running it with the local files (I was getting an error on including #include "opencv2/core/private.hpp" saying that "this is a private header which should not be used from outside of the OpenCV library" so i just commented it out)
```
==26287== Invalid read of size 32
==26287==    at 0x4430B6: cv::line_descriptor::BinaryDescriptor::computeLBD(std::vector<std::vector<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine, std::allocator<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine> >, std::allocator<std::vector<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine, std::allocator<cv::line_descriptor::BinaryDescriptor::OctaveSingleLine> > > >&, bool) (binary_descriptor.cpp:1356)
==26287==    by 0x443F5A: cv::line_descriptor::BinaryDescriptor::computeImpl(cv::Mat const&, std::vector<cv::line_descriptor::KeyLine, std::allocator<cv::line_descriptor::KeyLine> >&, cv::Mat&, bool, bool) const (binary_descriptor.cpp:640)
```
On going through binary_descriptor.cpp, I found that the below block of code is what is causing the problem
```.cpp
    cv::Mat appoggio = cv::Mat( 1, 32, CV_32FC1 );
    float* pointerToRow = appoggio.ptr<float>( 0 );
    for ( int g = 0; g < 32; g++ )
    {
      /* get LBD data */
      float* des_Vec = &keyLines[lineIDInScaleVec][0].descriptor.front();
      *pointerToRow = des_Vec[g]; 
      pointerToRow++;

    }
```
More specifically, the line 
```.cpp
       *pointerToRow = des_Vec[g];
``` 
is what is causing the crash.
I commented out that whole block of code  (lines 1350-1359), after which the program was working like a charm.

### PR DESCRIPTION
**Pull request by fallenlord**
resolves #1437

Using mask with cv::line_descriptor::BinaryDescriptor to detect feature lines, will get wrong results.

```cpp
Ptr<BinaryDescriptor> bd = BinaryDescriptor::createBinaryDescriptor();
Mat mask = Mat::zeros(src.size(), CV_8UC1);  // With all 0 mask should get no line
vector<KeyLine> lines;
bd->detect(src, lines, mask);  // Still get some lines
Mat desc;
bd->compute(src, lines, desc);  // Get NULL pointer exception
```

### This pullrequest changes

* Change BinaryDescriptor::detectImpl method: erasing an element from std::vector in the loop, should not always move iterator forward, let `keyCounter++` only call on no-erasing. This change make `bd->detect(...)` get correct masked key lines.
* Change BinaryDescriptor::computeLBD method: `float* des_Vec = &keyLines[lineIDInScaleVec][0].descriptor.front();` get NULL exception when using mask, add a check to avoid

```
force_builders=linux,windows,macosx,docs
```

### CODE REVIEW

File: modules/line_descriptor/src/binary_descriptor.cpp [hunk 1]
```diff
@@ -1347,6 +1349,9 @@ int BinaryDescriptor::computeLBD( ScaleLines &keyLines, bool useDetectionData )
     for ( int g = 0; g < 32; g++ )
     {
       /* get LBD data */
+      if (keyLines[lineIDInScaleVec].empty()) {
```
Comment (terfendail) [inline modules/line_descriptor/src/binary_descriptor.cpp]: It looks like this loop is used to fill `appogio` matrix. However it is a local matrix that will be discarded just after the loop. Is it necessary to fill it even if  `keyLines[lineIDInScaleVec]` isn't empty?

Comment (alalek) [reply modules/line_descriptor/src/binary_descriptor.cpp]: Perhaps initialization with zero values should work:
```
cv::Mat appoggio = cv::Mat(1, 32, CV_32FC1, Scalar::all(0));
```

**Comment by alalek** [comment]
Thank you for the contribution!

This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into 3.4 branch. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

File: modules/line_descriptor/src/binary_descriptor.cpp (hunk 1 above)
Comment (fallenlord) [reply modules/line_descriptor/src/binary_descriptor.cpp]: I reviewed the code again, and believe @terfendail is right. I removed the whole code block including appogio matrix and tested, it works perfectly.

**Comment by fallenlord** [comment]
@alalek Thank you for the guide, it's my first use PR, it's really helpful. 
I re-pushed the commits, with one more change (as @terfendail said, removing the whole block). 
Tell me if any other thing need to do, thank you.

**Comment by fallenlord** [comment]
A related bug found [here](https://github.com/opencv/opencv_contrib/issues/1437)
