### PR TITLE
solve issue #1155

### LINKED ISSUE #1155: Bug when sfm is called twice
Opencv 3.2-dev VS 2015 x64 win10
Hi,

When i call reconstruct function twice I have got this error message : 
```
Initialize nViewMatcher ... OK
Performing Cross Matching ... OK
F0511 09:30:29.707763 12244 utilities.cc:322] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
```

To reproduce this error message you can copy and paste [this line](https://github.com/opencv/opencv_contrib/blob/master/modules/sfm/samples/scene_reconstruction.cpp#L78) in sample scene_reconstruction.cpp  : 

```
/// Reconstruct the scene using the 2d images

  bool is_projective = true;
  vector<Mat> Rs_est, ts_est, points3d_estimated;
  reconstruct(images_paths, Rs_est, ts_est, K, points3d_estimated, is_projective);
  reconstruct(images_paths, Rs_est, ts_est, K, points3d_estimated, is_projective);


  // Print output

```

### PR DESCRIPTION
**Pull request by LaurentBerger**
resolves #1155

Add a static variable to avoid opening glog twice.
Add an example using [reconstruct ](http://docs.opencv.org/master/da/db5/group__reconstruction.html#gaadb8cc60069485cbb9273b1efebd757d)

### CODE REVIEW

File: modules/sfm/samples/match_reconstruct.cpp [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
...551513551607, 1042.6242747915535, 515.18516094478298, 1064.6864339428105, 517.0345166093, 1028.8265208422474, 630.75473327994234, 1010.1203860471132, 616.86908165559817, 996.19985447065733, 599.3243841996026, 988.33023759751575, 579.83863843873178, 987.19255503865372, 560.26867143621132, 992.84977172120693, 542.44788416870733, 1004.7580535827984, 528.03740660115034, 1021.816137753751, 518.39418344227761, 1042.44951185794, 514.45808391571939, 1064.7294016570784, 516.66192071592866, 1028.8265208422474, 630.75473327994234, 1017.5350185621438, 621.43804766425978, 1010.129091420788, 607.7697751504603, 1007.3782941632923, 591.07535887445397, 1009.5887692661379, 573.00838401730766, 1016.5588223557643, 555.38146636509168, 1027.592783283955, 539.971750817464, 1041.5742740659934, 528.32676718803498, 1057.0896910577135, 521.59772432873001, 1072.5841040247224, 520.42261009954859, 1023.6872850276745, 501.48463396235769, 1021.7363061422241, 497.10356942867941, 1149.394888427619, 563.63353085150766, 1144.1773056475884, 564.44012449568231, 975.13608212288557, 590.57245094776658, 970.39817079227953, 591.3048914910305, 1095.4493161212483, 662.63147754605677, 1093.3004875390534, 657.80612717419194));
```
Comment (sovrasov) [inline modules/sfm/samples/match_reconstruct.cpp]: I think it's better to move the data outside of the sample. Now user can't load his own data, so sample becomes almost useless.

**Comment by sovrasov** [comment]
👍
