### PR TITLE
FREAK : better rounding off for weighted dx and dy of orientation pairs

### LINKED ISSUE #2430: FREAK: invalid rounding of weight_d* of orientation pairs.
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
Link to the code: [.../freak.cpp#L286](https://github.com/opencv/opencv_contrib/blame/bdfd1e75d4805a7b938d3e7c6d95dcdb53ff7062/modules/xfeatures2d/src/freak.cpp#L286)
```
orientationPairs[m].weight_dx = int((dx/(norm_sq))*4096.0+0.5);
orientationPairs[m].weight_dy = int((dy/(norm_sq))*4096.0+0.5);
```

If my understand is correct, it's a rounding technique, isn't it? 

If so, when dx\dy are non-negatives, it's similar with "roundf".

**BUT if dx\dy are negatives, adding "0.5" seems wrong,**

for example:
**-1.3 --> 0** // -1.3+0.5=-0.8, and int(-0.8) = 0!

Isn't it "rounding" too much?

### PR DESCRIPTION
**Pull request by raanyild**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/721

resolves #2430, when value of dx/(norm_sq) is -ve, adding -0.5 will lead to better rounding off.

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!

As a "bugfix" this patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

File: modules/xfeatures2d/src/freak.cpp [hunk 1]
```diff
@@ -287,8 +287,8 @@ void FREAK_Impl::buildPattern()
         const float dx = patternLookup[orientationPairs[m].i].x-patternLookup[orientationPairs[m].j].x;
         const float dy = patternLookup[orientationPairs[m].i].y-patternLookup[orientationPairs[m].j].y;
         const float norm_sq = (dx*dx+dy*dy);
-        orientationPairs[m].weight_dx = int((dx/(norm_sq))*4096.0+0.5);
-        orientationPairs[m].weight_dy = int((dy/(norm_sq))*4096.0+0.5);
+        orientationPairs[m].weight_dx = int((dx/(norm_sq))*4096.0+0.5*((dx>0)-(dx<0)));
+        orientationPairs[m].weight_dy = int((dy/(norm_sq))*4096.0+0.5*((dy>0)-(dy<0)));
```
Comment (alalek) [inline modules/xfeatures2d/src/freak.cpp]: Please use `cvRound()` instead of 0.5 hack and "int" cast.

Another question is it allowed to weight_dx/dy become zero or negative?
Usually "weight" should not be negative. May be there is lost `abs()` call?

Comment (raanyild) [reply modules/xfeatures2d/src/freak.cpp]: weight_dx/dy can be negative to preserve the sense of direction
`direction0 += delta*(orientationPairs[m].weight_dx)/2048;`
`direction1 += delta*(orientationPairs[m].weight_dy)/2048;`
where delta is the difference in mean intensity between two pairs.

Comment (raanyild) [reply modules/xfeatures2d/src/freak.cpp]: But after using `cvRound()` tests are getting failed due to bad accuracy.

File: modules/xfeatures2d/src/freak.cpp [hunk 2]
```diff
@@ -675,10 +669,10 @@ imgType FREAK_Impl::meanIntensity( InputArray _image, InputArray _integral,
...
 
     // calculate borders
-    const int x_left = int(xf-radius+0.5);
-    const int y_top = int(yf-radius+0.5);
-    const int x_right = int(xf+radius+1.5);//integral image is 1px wider
-    const int y_bottom = int(yf+radius+1.5);//integral image is 1px higher
+    const int x_left = cvRound(xf-radius);
+    const int y_top = cvRound(yf-radius);
+    const int x_right = cvRound(xf+radius+1);//integral image is 1px wider
+    const int y_bottom = cvRound(yf+radius+1);//integral image is 1px higher
```
Comment (alalek) [inline modules/xfeatures2d/src/freak.cpp]: Why not just cvFloor() / cvCeil()?

Comment (raanyild) [reply modules/xfeatures2d/src/freak.cpp]: Suppose when `xf-radius` is 2.9 and 2.1, it will be more sensible to assign 3 and 2 respectively in `x_left`.

**Comment by raanyild** [comment]
I have sent a PR(opencv/opencv_extra#721) for updating test data.
