### PR TITLE
Fix popcnt errors for UWP ARM/ARM64

### LINKED ISSUE #2275: [saliency, line_descriptor, bgsegm] uwp-arm : error C3861: '__popcnt': identifier not found
##### System information (version)
- OpenCV => 4.1
- Operating System / Platform => Windows uwp ARM
- Compiler => Visual Studio 2017
building via vcpkg (see linked issue/discussion there: https://github.com/microsoft/vcpkg/issues/3278)

##### Detailed description
when building opencv-contrib for uwp arm, 3 modules fails with same error:
`error C3861: '__popcnt': identifier not found`
modules\saliency\src\BING\FilterTIG.cpp(58-59)
modules\line_descriptor\src\bitops.hpp(88-91)
modules\bgsegm\src\bgfg_gsoc.cpp(74)

##### Possible resolution
- fix the #if to correclty handle ARM (and ARM64?)
and
- use some generic popcnt macro from opencv if exists
- implement a pocnt macro that's independant from the platform (for 32b and 64b)
see implementation here http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetParallel

### PR DESCRIPTION
**Pull request by shimat**
## This pullrequest changes
Fix #2275

I use `_M_ARM` and `_M_ARM64` to determine if the platform is ARM or not.
https://docs.microsoft.com/ja-jp/cpp/preprocessor/predefined-macros?view=vs-2019

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
Xbuild_image:Win64=msvs2019-arm64
buildworker:Win64=windows-1
```

### CODE REVIEW

File: modules/bgsegm/src/bgfg_gsoc.cpp [hunk 1]
```diff
@@ -63,14 +63,14 @@ namespace
 
 const float LSBPtau = 0.05f;
 
-#ifdef _MSC_VER
+#if defined(_MSC_VER) && !(defined(_M_ARM) || defined(_M_ARM64))
```
Comment (shimat) [inline modules/bgsegm/src/bgfg_gsoc.cpp:66]:
```suggestion
#if defined(_MSC_VER) && !(defined(_M_ARM) || defined(_M_ARM64))
```

File: modules/bgsegm/src/bgfg_gsoc.cpp [hunk 2]
```diff
@@ -63,14 +63,14 @@ namespace
...
-#ifdef _MSC_VER
+#if defined(_MSC_VER) && !(defined(_M_ARM) || defined(_M_ARM64)) 
 #include <intrin.h>
 #pragma intrinsic(__popcnt)
 #endif
 inline int LSBPDist32(unsigned n) {
 #if defined(__GNUC__) || defined(__clang__)
     return __builtin_popcount(n);
-#elif defined(_MSC_VER)
+#elif defined(_MSC_VER) && !(defined(_M_ARM) || defined(_M_ARM64))
```
Comment (shimat) [inline modules/bgsegm/src/bgfg_gsoc.cpp:73]:
```suggestion
#elif defined(_MSC_VER) && !(defined(_M_ARM) || defined(_M_ARM64))
```

**Comment by alalek** [comment]
Thank you for contribution!

This patch should go into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- **[preferred]** squash commits into one
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

---

Please ignore "Win64" builder for now - it is used for customized Windows ARM64 build (not supported configuration).

**Comment by shimat** [comment]
Thank you. I have done the procedure.
