### PR TITLE
bgsegm: gmg: Relax source type and add test

### LINKED ISSUE #3756: test bgsegm will random fail
## System information (version)

- OpenCV => 4.x
- Operating System / Platform => ?
- Compiler => ?

## Detailed description

https://github.com/opencv/opencv_contrib/blob/4.x/modules/bgsegm/test/test_backgroundsubtractor_gbh.cpp#L31
``` cpp
RNG& rng = ts->get_rng();
int type = ((unsigned int)rng)%7;  //!< pick a random type, 0 - 6, defined in types_c.h
int channels = 1 + ((unsigned int)rng)%4;  //!< random number of channels from 1 to 4.
int channelsAndType = CV_MAKETYPE(type,channels);
```

https://github.com/opencv/opencv_contrib/blob/4.x/modules/bgsegm/src/bgfg_gmg.cpp#L429
``` cpp
CV_Assert(frame.depth() == CV_8U || frame.depth() == CV_16U || frame.depth() == CV_32F);
CV_Assert(frame.channels() == 1 || frame.channels() == 3 || frame.channels() == 4);
```

## Steps to reproduce

https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101170/steps/test_bgsegm/logs/stdio
https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_windows64/builds/100771/steps/test_bgsegm/logs/stdio

And others' builds:

https://github.com/opencv/opencv_contrib/actions/runs/9416634089/job/25997503170?pr=3755
https://github.com/opencv/opencv_contrib/actions/runs/9416634089/job/25997503279?pr=3755

https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101174/steps/test_bgsegm/logs/stdio
https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_windows64/builds/100775/steps/test_bgsegm/logs/stdio

All have no any change on besegm.

```
/build/precommit-contrib_linux64/4.x/opencv/modules/ts/src/ts.cpp:616: Failure
Failed

	failure reason: cvError invoked
	test case #-1
	seed: 0000000000000000
-----------------------------------
	LOG:
OpenCV Error:
	Assertion failed (frame.depth() == CV_8U || frame.depth() == CV_16U || frame.depth() == CV_32F) in apply, file /build/precommit-contrib_linux64/4.x/opencv_contrib/modules/bgsegm/src/bgfg_gmg.cpp, line 429
OpenCV Error:
	Assertion failed (frame.depth() == CV_8U || frame.depth() == CV_16U || frame.depth() == CV_32F) in apply, file /build/precommit-contrib_linux64/4.x/opencv_contrib/modules/bgsegm/src/bgfg_gmg.cpp, line 429

-----------------------------------

[  FAILED  ] VIDEO_BGSUBGMG.accuracy (0 ms)
```

I run `opencv_test_bgsegm` on my PC, the rng state in this test is always 18446744073709551615, thus `channelsAndType = CV8UC1`.

Notice the seed above test log said is not the `rng` in test.

https://github.com/opencv/opencv/blob/4.x/modules/ts/src/ts.cpp#L604
``` cpp
snprintf(seedstr, sizeof(seedstr), "%08x%08x", (unsigned)(current_test_info.rng_seed>>32),
                            (unsigned)(current_test_info.rng_seed));
```

https://github.com/opencv/opencv/blob/4.x/modules/ts/include/opencv2/ts.hpp#L614
```cpp
RNG& get_rng() { return cv::theRNG(); }
```
And if we do not need random, maybe just `channelsAndType = CV8UC1` will be more clear?

It maybe affect all PRs on `opencv_contrib`.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by Kumataro**
Close #3756 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/bgsegm/test/test_backgroundsubtractor_gbh.cpp [hunk 1]
```diff
@@ -132,6 +132,19 @@ void CV_BackgroundSubtractorTest::run(int)
 
 }
 
-TEST(VIDEO_BGSUBGMG, accuracy) { CV_BackgroundSubtractorTest test; test.safe_run(); }
+typedef testing::TestWithParam<std::tuple<perf::MatDepth,int>> bgsubgmg_allTypes;
+TEST_P(bgsubgmg_allTypes, accuracy)
+{
+    const int mtype = CV_MAKETYPE(get<0>(GetParam()), get<1>(GetParam()));
+    CV_BackgroundSubtractorTest test;
```
Comment (mshabunin) [inline modules/bgsegm/test/test_backgroundsubtractor_gbh.cpp:139]: Perhaps the whole test can be reworked in modern style since you've already done large part of this task. In order to do this we need to:
1. Remove `CV_BackgroundSubtractorTest` class and move whole `run` function body to the test body (`mtype` becomes local variable)
2. Use `cv::theRNG()` or `TS::ptr()->get_rng()` for `rng`
3. Use proper `EXPECT_/ASSERT_` macros for error checking instead of `CV_Assert` and `ts->set_failed_test_info(...)`. It can be as simple as just using `EXPECT_GE(TS::ptr()->cmpEps2(...), 0)` or slightly more  changed, e.g. `EXPECT_MAT_NEAR(... ,..., ...)` or `EXPECT_LT(norm(..., ..., ...), some_eps)`

Comment (Kumataro) [reply modules/bgsegm/test/test_backgroundsubtractor_gbh.cpp]: Thank you for your comment ! I fixed them.

**Review by mshabunin — APPROVED** [review]
