### PR TITLE
Contrib.java.wrapper.fix.3.2

### LINKED ISSUE #1188: Fix java wrappers to cv::text::ERFilter constructors
##### System information (version)

- OpenCV => 3.2 master (78fabfe606d99e1dd1083c340457fe0e9d889a56)
- Operating System / Platform => OSX El Capitain 10.11.6 (15G1421)
- Compiler => Xcode Version 8.1 (8B62)

##### Detailed description

Enabling java wrapper generation for Text module is not producing usable wrappers for ERFilter, because constructors createERFilterNM1, createERFilterNM2 use Callback parameter, which is not translated to java so proper wrappers for these constructors are not generated.

##### Steps to reproduce
1. Enable generation of java wrappers in CMakeLists.txt for Text module
2. Build opencv with contrib and java enabled. Resulting warppers are non usable because createERFilterNM1/2() constructors are not wrapped.

### PR DESCRIPTION
**Pull request by abratchik**
### This pullrequest changes

resolves #1188 

additional constructors were added to ERFilter class where the callback parameter has been replaced with the String designating the filename of the XML or YAML file with the classifier model (e.g. trained_classifierNM1.xml):

```
CV_EXPORTS_W  Ptr<ERFilter> createERFilterNM1(const String& filename,
                                                  int thresholdDelta = 1, float minArea = (float)0.00025,
                                                  float maxArea = (float)0.13, float minProbability = (float)0.4,
                                                  bool nonMaxSuppression = true,
                                                  float minProbabilityDiff = (float)0.1);
```

```
CV_EXPORTS_W Ptr<ERFilter> createERFilterNM2(const String& filename,
                                                  float minProbability = (float)0.3);

```

The example of calling these constructors from Java:

```
ERFilter erc1 = Text.createERFilterNM1(strClassifierNM1Path,16,0.00015f,0.13f,0.2f,true,0.1f);
ERFilter erc2 = Text.createERFilterNM2(strClassifierNM2Path, 0.5f); 
```

### CODE REVIEW

File: modules/text/include/opencv2/text/erfilter.hpp [hunk 1]
```diff
@@ -227,6 +227,11 @@ features: hole area ratio, convex hull ratio, and number of outer inflexion poin
 CV_EXPORTS_W Ptr<ERFilter> createERFilterNM2(const Ptr<ERFilter::Callback>& cb,
                                                   float minProbability = (float)0.3);
 
+CV_EXPORTS_W  Ptr<ERFilter> createERFilterNM1(const String& filename,
```
Comment (sovrasov) [inline modules/text/include/opencv2/text/erfilter.hpp]: The new constructors should be documented.

Comment (abratchik) [inline modules/text/include/opencv2/text/erfilter.hpp]: Could you please guide me where I need to provide documentation? If I just add comments would it be sufficient?

Comment (sovrasov) [inline modules/text/include/opencv2/text/erfilter.hpp]: Documentation in our case is comments of spacial type. Take a look at the previous constructor in this file. I'ts [documented](https://github.com/abratchik/opencv_contrib/blob/59df3bf5421c95dda7ddd22cbf6c78f23c647e41/modules/text/include/opencv2/text/erfilter.hpp#L216-L226).

File: modules/text/include/opencv2/text/erfilter.hpp [hunk 2]
```diff
@@ -227,6 +227,43 @@ features: hole area ratio, convex hull ratio, and number of outer inflexion poin
...
+
+@param  filename :   The path to the classifier XML, e.g. /path/to/cpp/trained_classifierNM1.xml
+@param  thresholdDelta :   Threshold step in subsequent thresholds when extracting the component tree
+@param  minArea :   The minimum area (% of image size) allowed for retreived ER's
+@param  maxArea :   The maximum area (% of image size) allowed for retreived ER's
+@param  minProbability :   The minimum probability P(er|character) allowed for retreived ER's
+@param  nonMaxSuppression :   Whenever non-maximum suppression is done over the branch probabilities
+@param  minProbabilityDiff :   The minimum probability difference between local maxima and local minima ERs
+
+The component tree of the image is extracted by a threshold increased step by step from 0 to 255,
```
Comment (sovrasov) [inline modules/text/include/opencv2/text/erfilter.hpp]: This part of description is redundant, it's better to make a reference to the previous constructor.

File: modules/text/include/opencv2/text/erfilter.hpp [hunk 3]
```diff
@@ -227,6 +227,43 @@ features: hole area ratio, convex hull ratio, and number of outer inflexion poin
...
+                                                  float maxArea = (float)0.13, float minProbability = (float)0.4,
+                                                  bool nonMaxSuppression = true,
+                                                  float minProbabilityDiff = (float)0.1);
+
+/** @brief Create an Extremal Region Filter for the 2nd stage classifier of N&M algorithm [Neumann12].
+
+@param  filename :   The path to the classifier XML, e.g. /path/to/cpp/trained_classifierNM2.xml
+@param  minProbability :   The minimum probability P(er|character) allowed for retreived ER's
+
+In the second stage, the ERs that passed the first stage are classified into character and
```
Comment (sovrasov) [inline modules/text/include/opencv2/text/erfilter.hpp]: The same thing about detailed description here.

Comment (abratchik) [inline modules/text/include/opencv2/text/erfilter.hpp]: Hi sovrasov,

I'm not very strong with doxygen - do you mind sharing some examples how I need to document such cases?

File: modules/text/include/opencv2/text/erfilter.hpp (hunk 2 above)
Comment (sovrasov) [inline modules/text/include/opencv2/text/erfilter.hpp]: @abratchik  Here can be something like this instead of the long description.
```
/** @brief Reads an Extremal Region Filter for the 1st stage classifier of N&M algorithm
    from the provided path e.g. /path/to/cpp/trained_classifierNM1.xml
@overload
 */
```

**Comment by sovrasov** [comment]
Please, squash commits into one before merge.

**Comment by sovrasov** [comment]
:+1:

**Comment by abratchik** [comment]
Hi, Vladislav. If I have more of the similar changes in the Text module, should I push under this oull request or need to open a new one? I'd like to be able to create all BaseOCR children and not only OCR Tesseract.

**Comment by alalek** [comment]
@abratchik Please open a new PR with a reference(link) on this.
